name: Pull request checks

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

env:
  ga_node_version: 22

jobs:
  lintcheck:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js with version ${{ ga_node_version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ ga_node_version }}

      - name: Install npm dependencies
        run: npm ci
        shell: bash

      - name: Run linters
        run: npm run stylelint
